### ISSUE TITLE
Full transformation from XML to an object model

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/PyCrop2ML#12]
Currently, objects are created from XML.
However, the parsing is incomplete.
Define the full conceptual object model, and then fill it from xml.

Moreover, generate xml files from the objects.

**Comment by pradal** [comment]
Close this issue when ready

**Comment by cyrillemidingoyi** [comment]
ok, I'm updating pparse to take into account the new concepts (eg. algorithm in src directory)
