### ISSUE TITLE
Move Continuous Integration to Github Actions

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/PyCrop2ML#134]
Move AppVeyor and Travis to Github Actions

**Comment by pradal** [comment]
@CyrilleAhmed I will do it.
We havedevelopped  a systematic action in OpenAlea

**Comment by cyrillemidingoyi** [comment]
Ok @pradal

**Comment by pradal** [comment]
@cyrillemidingoyi 
I have made the packaging on conda branch.
But the action fail. If you can look at...
