### ISSUE TITLE
Is pi already define?

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/PyCrop2ML#190]
An error occurs when we define 
`v * pi`

Is $\pi$ is managed by Crop2ML?

**Comment by cyrillemidingoyi** [comment]
@pradal
yes, CyML handles pi constant from math library

#CyML
source = """
from math import *
def test(int a):
    return a * pi
"""
# C++ generated
#define _USE_MATH_DEFINES
#include <cmath>
using namespace std;
double test(int a)
{
    return a * M_PI;
}
#endif
