### ISSUE TITLE
convert xml to json - simplify function calls

### ISSUE THREAD

**Issue by cyrillemidingoyi** [AgriculturalModelExchangeInitiative/PyCrop2ML#20]
Objectives:
[ ] implement a class that parses xml file and transform it in json
[ ] Define the JSON schema in json and validate it using jsonschema
[ ] a function that calls  parsing and render in order to access xml files for notebook generation
(Review render structure)

**Comment by pradal** [comment]
I have seen three different packages:
- [xml2dict](https://github.com/martinblech/xmltodict) which is the most popular. However, it has some inherent limitations.
- [xmljson](https://github.com/sanand0/xmljson): A recent module to convert in different ways xml to Python
- [jxmlease](https://github.com/Juniper/jxmlease) : The advantage of this module is that it keeps all the xml information inside the Python classes to regenrate the initial xml. An extensive explanation is done in the following article : [jxmlease-python-xml-conversion-data-structures](https://www.oreilly.com/learning/jxmlease-python-xml-conversion-data-structures)

However, all these modules are quite similar.

**Comment by pradal** [comment]
Outdated
