### ISSUE TITLE
Model composition in CropML

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/PyCrop2ML#23]
Add the composition of models in xml/dtd.
The composition follows the composite design pattern.

A model is either:

- a model uint(atomic)
- or a model composite , that is a model that is composed of models ( unit or composite)

The composition is  represented as a **directed** port graph of models:

- **Vertices** are the different models that form the composition.
- **Ports** are the inputs and outputs of each model.
- **Edges** are directed and connect one output port to an input port of another model.

A description of such *workflow* or composite model can be found at https://github.com/openalea/wlformat

**Comment by pradal** [comment]
@cyrillemidingoyi Close when done.

**Comment by cyrillemidingoyi** [comment]
Done
