### ISSUE TITLE
transpilation package

### ISSUE THREAD

**Issue by cyrillemidingoyi** [AgriculturalModelExchangeInitiative/PyCrop2ML#40]
@pradal 
Hi, please, you can access the transpilation architecture on wiki.
I tried to have a same design for each language without a descriptive template. Each language has its code generation which inherit from CodeGenerator class.
I will continue to write all the rules of code tranformation in the module rule of each language
[https://github.com/AgriculturalModelExchangeInitiative/PyCrop2ML/wiki/Transpilation-workflow](url)

**Comment by pradal** [comment]
Done
